#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usermode
Version  : 1.113
Release  : 15
URL      : https://releases.pagure.org/usermode/usermode-1.113.tar.xz
Source0  : https://releases.pagure.org/usermode/usermode-1.113.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: usermode-bin = %{version}-%{release}
Requires: usermode-data = %{version}-%{release}
Requires: usermode-license = %{version}-%{release}
Requires: usermode-locales = %{version}-%{release}
Requires: usermode-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : desktop-file-utils
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libstartup-notification-1.0)
BuildRequires : pkgconfig(libuser)
BuildRequires : pkgconfig(sm)
BuildRequires : startup-notification

%description
About
=====
usermode contains the userhelper program, which can be used to allow configured
programs to be run with superuser privileges by ordinary users, and several
graphical tools for users:
* userinfo allows users to change their finger information.
* usermount lets users mount, unmount, and format filesystems.
* userpasswd allows users to change their passwords.

%package bin
Summary: bin components for the usermode package.
Group: Binaries
Requires: usermode-data = %{version}-%{release}
Requires: usermode-license = %{version}-%{release}

%description bin
bin components for the usermode package.


%package data
Summary: data components for the usermode package.
Group: Data

%description data
data components for the usermode package.


%package extras
Summary: extras components for the usermode package.
Group: Default

%description extras
extras components for the usermode package.


%package license
Summary: license components for the usermode package.
Group: Default

%description license
license components for the usermode package.


%package locales
Summary: locales components for the usermode package.
Group: Default

%description locales
locales components for the usermode package.


%package man
Summary: man components for the usermode package.
Group: Default

%description man
man components for the usermode package.


%prep
%setup -q -n usermode-1.113
cd %{_builddir}/usermode-1.113

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604600399
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604600399
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/usermode
cp %{_builddir}/usermode-1.113/COPYING %{buildroot}/usr/share/package-licenses/usermode/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
%make_install
%find_lang usermode

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/consolehelper
/usr/bin/userhelper

%files data
%defattr(-,root,root,-)
/usr/share/pixmaps/badge-small.png
/usr/share/pixmaps/disks.png
/usr/share/pixmaps/keyring.png
/usr/share/pixmaps/keys.xpm
/usr/share/pixmaps/password.png
/usr/share/pixmaps/status_lock.png
/usr/share/pixmaps/status_unlocked.png
/usr/share/pixmaps/user_icon.png
/usr/share/usermode/usermode.ui

%files extras
%defattr(-,root,root,-)
/usr/bin/consolehelper-gtk
/usr/bin/pam-panel-icon
/usr/bin/userinfo
/usr/bin/usermount
/usr/bin/userpasswd
/usr/share/applications/redhat-userinfo.desktop
/usr/share/applications/redhat-usermount.desktop
/usr/share/applications/redhat-userpasswd.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/usermode/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pam-panel-icon.1
/usr/share/man/man1/userinfo.1
/usr/share/man/man1/usermount.1
/usr/share/man/man1/userpasswd.1
/usr/share/man/man8/consolehelper-gtk.8
/usr/share/man/man8/consolehelper.8
/usr/share/man/man8/userhelper.8

%files locales -f usermode.lang
%defattr(-,root,root,-)

