#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usermode
Version  : 1.111
Release  : 9
URL      : http://releases.pagure.org/usermode/usermode-1.111.tar.xz
Source0  : http://releases.pagure.org/usermode/usermode-1.111.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: usermode-bin
Requires: usermode-data
Requires: usermode-locales
Requires: usermode-doc
BuildRequires : Linux-PAM-dev
BuildRequires : desktop-file-utils
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libstartup-notification-1.0)
BuildRequires : pkgconfig(libuser)
BuildRequires : pkgconfig(sm)
BuildRequires : startup-notification
BuildRequires : util-linux-dev

%description
About
=====
usermode contains the userhelper program, which can be used to allow configured
programs to be run with superuser privileges by ordinary users, and several
graphical tools for users:
* userinfo allows users to change their finger information.
* usermount lets users mount, unmount, and format filesystems.
* userpasswd allows users to change their passwords.

%package bin
Summary: bin components for the usermode package.
Group: Binaries
Requires: usermode-data

%description bin
bin components for the usermode package.


%package data
Summary: data components for the usermode package.
Group: Data

%description data
data components for the usermode package.


%package doc
Summary: doc components for the usermode package.
Group: Documentation

%description doc
doc components for the usermode package.


%package extras
Summary: extras components for the usermode package.
Group: Default

%description extras
extras components for the usermode package.


%package locales
Summary: locales components for the usermode package.
Group: Default

%description locales
locales components for the usermode package.


%prep
%setup -q -n usermode-1.111

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494962433
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1494962433
rm -rf %{buildroot}
%make_install
%find_lang usermode

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/consolehelper-gtk
%exclude /usr/bin/pam-panel-icon
%exclude /usr/bin/userinfo
%exclude /usr/bin/usermount
%exclude /usr/bin/userpasswd
/usr/bin/consolehelper
/usr/bin/userhelper

%files data
%defattr(-,root,root,-)
/usr/share/applications/redhat-userinfo.desktop
/usr/share/applications/redhat-usermount.desktop
/usr/share/applications/redhat-userpasswd.desktop
/usr/share/pixmaps/badge-small.png
/usr/share/pixmaps/disks.png
/usr/share/pixmaps/keyring.png
/usr/share/pixmaps/keys.xpm
/usr/share/pixmaps/password.png
/usr/share/pixmaps/status_lock.png
/usr/share/pixmaps/status_unlocked.png
/usr/share/pixmaps/user_icon.png
/usr/share/usermode/usermode.ui

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man8/*

%files extras
%defattr(-,root,root,-)
/usr/bin/consolehelper-gtk
/usr/bin/pam-panel-icon
/usr/bin/userinfo
/usr/bin/usermount
/usr/bin/userpasswd

%files locales -f usermode.lang
%defattr(-,root,root,-)

